server:
  port: 9000

spring:
  application:
    name: microservice-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice_auth
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    jwt:
      expiration: 3600000 
logging:
  level:
    org.springframework.security: DEBUG
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

