server:
  port: 8080

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clients
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/clients/**
        - id: products
          uri: 'http://localhost:8092'
          predicates:
            - Path=/api/products/**
        - id: orders
          uri: 'http://localhost:8091'
          predicates:
            - Path=/api/orders/**
        - id: auth
          uri: 'http://localhost:9000'
          predicates:
            - Path=/auth/**
            - Path=/key/**
  
eureka:
  client:
    register-with-eureka: false
    
